#! /bin/sh
# $Id$

{
  for dir in `echo "$PATH" \
               | sed -e 's/^:/.:/;s/::/:.:/g;s/:$/:./;s/:/ /g'`
  do
    ls -1a "$dir" \
      | grep -i "$1" \
      | {
          while read f; do
            test -f "$dir/$f" && test -x "$dir/$f" && echo "$f"
          done
        }
  done
} | sort -u

# eof
