#!/bin/sh
# $Id: automake-ify,v 1.2 2005/12/27 05:08:27 friedman Exp $

run()
{
  echo ${PS4-+} ${1+"$@"} 1>&2
  ${1+"$@"} || exit $?
}

run aclocal

if [ -d po ]; then
  run glib-gettextize --force --copy
fi

run autoheader

if [ -f Makefile.am ]; then
  run automake --add-missing --copy
fi

run autoconf
