#!/bin/sh
# $Id: automake-ify,v 1.5 2010/09/19 07:00:19 friedman Exp $

run()
{
  echo ${PS4-+} ${1+"$@"} 1>&2
  ${1+"$@"} || exit $?
}

if [ -d m4 ]; then
  run aclocal -I m4
else
  run aclocal
fi

if [ -d po ]; then
  run glib-gettextize --force --copy
fi

run autoheader

if grep 'AM_PROG_LIBTOOL' configure.in > /dev/null 2>&1; then
  if grep -i 'libltdl' configure.in > /dev/null 2>&1; then
    if [ -d libltdl ]; then
      rm -rf libltdl
    fi
    run libtoolize -c --ltdl --subproject
  else
    run libtoolize -c
  fi
fi

if [ -f Makefile.am ]; then
  run automake --add-missing --copy
fi

run autoconf
