#!/bin/sh
exec ${PERL-perl} -Sx $0 ${1+"$@"}
#!perl

# $Id: dateclock,v 1.1 2000/03/09 20:14:02 friedman Exp $

use POSIX;

$| = 1;
while (1)
  {
    print strftime ("\r%a %b %e %H:%M:%S %Z %Y", localtime ());
    select (undef, undef, undef, 0.50);
  }

# local variables:
# mode: perl
# end:
