#!/usr/bin/env perl
# $Id: dateclock,v 1.2 2002/09/12 10:07:50 friedman Exp $

use POSIX;

$| = 1;
while (1)
  {
    print strftime ("\r%Y-%m-%d %H:%M:%S %z", localtime),
          strftime (" %H:%MZ", gmtime);
    select (undef, undef, undef, 0.50);
  }

# eof
