#!/bin/sh
# $Id: delete-backups,v 1.2 2000/02/07 08:21:00 friedman Exp $

case "$#" in
  0 ) echo "Usage: delete-backups [dir]" 1>&2; exit 1 ;;
esac

ver=`xargs --version 2>&1 < /dev/null`

case $ver in
  *GNU* )
    find ${1+"$@"} \( -name '.*~' -o -name '*~' -o -name '#*#' \) -print0 \
      | xargs --no-run-if-empty --null rm -vf
   ;;
  * )
    find ${1+"$@"} \( -name '.*~' -o -name '*~' -o -name '#*#' \) -print \
     | xargs rm -f
   ;;
esac
