#!/bin/sh

: ${FIND:=find}
: ${RM:=rm}
: ${SORT:=sort}
: ${TOUCH:=touch}
: ${ZIP:=zip}
: ${ZLEVEL:=9}

while [ $# -gt 0 ]; do
    case $1 in
        -[0-9] ) ZLEVEL=${1#-} ;;
        * ) break ;;
    esac
    shift
done

for dir in "$@" ; do
    # Protect against accidental trailing slash, i.e. if someone does
    # dist-zip foo/, don't create foo/.zip only to delete foo afterward.
    while :; do
        case $dir in
            */ ) dir=${dir%/} ;;
            *  ) break ;;
        esac
    done

    echo "dist-zip: packing $dir.zip"

    { $FIND "$dir" -print \
          | $SORT \
          | $ZIP -$ZLEVEL -y -@ "$dir.zip"
    } && $TOUCH -r "$dir" "$dir.zip" \
      && $RM   -fr "$dir"
done

# eof
