#! /bin/sh
# $Id: dist-tar,v 1.1 1997/09/23 19:27:42 friedman Exp $

LC_COLLATE=C
export LC_COLLATE

if ${TAR-tar} --version 2>&1 | grep 'GNU tar' > /dev/null; then
  gnutar=t
fi

for dir in ${1+"$@"} ; do
  # Protect against accidental trailing slash, i.e. if someone does
  # dist-tar foo/, don't create foo/.tar.gz only to delete foo
  # afterward.
  case $dir in
    */ ) dir=`echo "$dir" | sed -e 's=/$==g'` ;;
  esac

  echo "dist-tar: packing $dir.tar.gz"

  { case $gnutar in
      t ) find "$dir" -print \
           | sort \
           | ${TAR-tar} --no-recursion -T - -cvf - \
           | gzip --best > "$dir.tar.gz" ;;

      * ) ${TAR-tar} -cvf - "$dir" \
           | gzip --best > "$dir.tar.gz" ;;
    esac
  } && touch -r "$dir" "$dir.tar.gz" \
    && rm -rf "$dir"
done

# eof
