#!/bin/sh
# $Id: dist-tar,v 1.10 2017/09/30 01:09:27 friedman Exp $

LC_COLLATE=C
export LC_COLLATE

cmdp() { type "$@" > /dev/null 2>&1; }
case ${FIND-nil} in nil ) if cmdp gfind; then FIND=gfind; fi ;; esac
case ${TAR-nil}  in nil ) if cmdp gtar;  then TAR=gtar;   fi ;; esac
case ${SORT-nil} in nil ) if cmdp gsort; then SORT=gsort; fi ;; esac

: ${ZLEVEL:=9}
: ${DIST_TAR_ZIP:=gzip}

while [ $# -gt 0 ]; do
    case $1 in
        -gz    ) DIST_TAR_ZIP=gzip  ;;
        -bz2   ) DIST_TAR_ZIP=bzip2 ;;
        -gzip | -bzip2 | -lzma | -xz ) DIST_TAR_ZIP=${1#-} ;;
        -[0-9] ) ZLEVEL=${1#-} ;;
        -u*    ) TAROPT="$TAROPT --owner=${1#-u}" ;;
        -g*    ) TAROPT="$TAROPT --group=${1#-g}" ;;
        -o*    ) TAROPT="$TAROPT --owner=${1#-o} --group=${1#-o}" ;;
        -m*    ) TAROPT="$TAROPT --mode=${1#-m}"  ;;
        -n     ) TAROPT="$TAROPT --numeric-owner" ;;
        * ) break ;;
    esac
    shift
done

gnup() { "$1" --version 2>&1 | grep "GNU" > /dev/null; }
if gnup ${TAR-tar}; then
    gnutar=t
    if gnup ${FIND-find} && gnup ${SORT-sort}; then
        FPRINT=print0
        SORTOPT="$SORTOPT --zero-terminated"
        TAROPT="$TAROPT --null"
    fi
fi

zip=$DIST_TAR_ZIP
z=${DIST_TAR_ZIP##*/}
zargs=-$ZLEVEL
case ${zip##*/} in
    gzip  ) z=gz  ;;
    bzip2 ) z=bz2 ;;
    xz | lzma )
        if [ $ZLEVEL -gt 3 ]; then
            zargs="$zargs --threads=0"
        fi ;;
    * ) echo "dist-tar: $DIST_TAR_ZIP: unknown compression method" 1>&2
        exit 1 ;;
esac

for dir in "$@" ; do
    # Protect against accidental trailing slash, i.e. if someone does
    # dist-tar foo/, don't create foo/.tar.gz only to delete foo after.
    dir=${dir%/}
    { case $gnutar in
          t ) echo "dist-tar: (gnu) packing $dir.tar.$z"
              ${FIND-find} "$dir" -${FPRINT-print} \
                  | ${SORT-sort} $SORTOPT \
                  | ${TAR-tar} $TAROPT --no-recursion -T - -cvf - \
                  | $zip $zargs > "$dir.tar.$z" ;;

          * ) echo "dist-tar: packing $dir.tar.$z"
              ${TAR-tar} $TAROPT -cvf - "$dir" \
                  | $zip $zargs > "$dir.tar.$z" ;;
      esac
    } && touch -r "$dir" "$dir.tar.$z" \
      && rm -rf "$dir"
done

# eof
