#!/bin/sh
# domrev --- Reverse domain names or IP addresses
# Author: Noah Friedman <friedman@prep.ai.mit.edu>
# Created: 1994-10-10
# Public domain

# $Id$

echo "$@" | sed -ne '
   H
   x
   s/$/./
   :1
   /\n$/!{
      s/\(.*\)\(\n.*\)\([^.][^.]*.\)$/\1\3\2/
      b 1
   }
   s/\.\n$//
   p'

# domrev ends here
