#!/bin/sh

sedcmd='h
        s/[^:]*://
        H
        g
        s/\n.*//
        s/:.*//
        s/^\///
        s/^[^@]*@//
        s/^/@/
        :1
        s/\([^@]*\)@\(.*\)\.\([^.][^.]*\)$/\1\/\3@\2/
        t 1
        s/@/\//
        x
        s/.*\n//
        H
        x
        s/\n//
        s/^/\/alex/
        p'

if test $# -eq 0 ; then
   exec sed -n "${sedcmd}"
else
   echo ${1+"$@"} | sed -n "${sedcmd}"
fi

# eof
