#!/usr/local/bin/perl

@time_mult = (31536000, 2592000, 86400, 3600,   60,       1);
@time_name = ("year",   "month", "day", "hour", "minute", "second");

for ($argc = 0; $argc <= $#ARGV; $argc += 1)
  {
    @st = stat("$ARGV[$argc]");
    # If st_ino is 0, file didn't exist. 
    if ($st[1] == 0) 
      { 
        print (STDERR "$ARGV[0]: $!\n");
        last;
      }

    $seconds = time () - $st[9];

    $output = "";
    for ($i = 0; $i <= $#time_mult; $i += 1)
      {
        $val = int ($seconds / $time_mult[$i]);
        $seconds -= $val * $time_mult[$i];
        if ($val != 0 || (length ($output) == 0 && $i == $#time_mult))
          {
            if (length ($output) > 0)
              {
                $output = "$output" . ", ";
              }
            $output = "$output" . "$val $time_name[$i]" ;
            if ($val != 1)
              {
                $output = "$output" . "s" ;
              }
          }
      }
    if ($#ARGV >= 1)
      {
        print("$ARGV[$argc]: ");
      }
    print ("$output\n");
  }
