#! /bin/sh
# $Id: find-ssh-agent,v 1.2 2000/04/10 09:12:02 friedman Exp $

listkeys=
case "$1" in
  -k ) listkeys=t ;;
  -e ) printeval=t ;;
esac

for try in /tmp/ssh-${LOGNAME-${USER-`whoami`}}/ssh-*-agent \
           /tmp/ssh-*/agent.*
do
  got=`SSH_AUTHENTICATION_SOCKET=$try SSH_AUTH_SOCK=$try ssh-add -l 2>/dev/null`
  case "$got" in
    '' ) : ;;
    * )
      case "$printeval" in
        t )
          echo "SSH_AUTH_SOCK=$try"
          echo "export SSH_AUTH_SOCK"
          exit 0
         ;;
      esac
      echo $try
      case "$listkeys" in
        t )
          echo "$got" \
            | sed -e '/^[0-9][0-9]*  *[0-9][0-9]*  *[0-9][0-9]*  */{
                        s///
                      }
                      s/^/   /
                     '
          echo
       ;;
      esac
     ;;
  esac
done
