#!/bin/sh
# $Id$

decode_flac()
{
  flac --silent --force --decode "$@"
}

encode_mp3()
{
  set x --nohist -h -p --preset standard "$@"
  shift
  if ! [ -t 1 ]; then set x --silent; shift; fi

  lame "$@"
}

flac_to_mp3()
{
  flac=$1
  base=`basename "$flac" .flac`
  wav=_flac2mp3_$$.wav
  mp3=$base.mp3

  decode_flac -o "$wav" "$flac" &&
  encode_mp3 "$wav" "$mp3"
  rm -f "$wav"
}

main()
{
  for f in "$@"; do
    echo "$f"
    flac_to_mp3 "$f"
    echo
  done
}

main "$@"

# eof
