#! /bin/sh
# http-proxy
# Author: Noah Friedman <friedman@prep.ai.mit.edu>
# Created: 1996-09-23
# Public domain.

# $Id$

PATH="$PATH:/usr/local/etc"
export PATH

read line
eval `echo "$line" \
       | sed -ne '
           s/[ 	][ 	]*/ /g
           h
           g
           s/^/method=/
           s/ .*//p
           g

           s/^[^ ]* //
           s/ .*//
           s/^http:\/\///
           /^[^/]*:[0-9]/!s/\([^/]*\)/\1:80/
           s/\([^:]*\):\([0-9]*\)\(\/.*\)/host="\1" port="\2" url="\3"/p

           g
           s/^[^ ]* [^ ]* *//
           s/ *$//
           s/^/protocol=/p'`

{
  echo "$method $url $protocol"
  cat
} | tcpconnect $host $port

# eof
