#!/bin/sh
# $Id: links-dump,v 1.1 2013/04/08 21:18:19 friedman Exp $

exec ${LINKS-elinks}        \
    -dump                   \
    -dump-width       80    \
    -dump-charset     utf-8 \
    -no-connect        1    \
    -no-home           1    \
    -no-numbering           \
    -no-references          \
    "$@"

# eof
