#! /bin/sh
# marchie --- pretty front end for typical archie sessions
# Author: Noah Friedman <friedman@prep.ai.mit.edu>
# Created: 1995-06-12
# Public domain

# $Id$

# Commentary:

# This script fetches output from archie and formats entries one-per-line
# in the form
#
#   size url
#
# e.g.:     1729 ftp://prep.ai.mit.edu/pub/gnu/README

# Other reasonably fast archie servers:
#       archie.doc.ic.ac.uk
#       archie.unit.no
#       archie.au

# Code:

archie -h archie.unit.no -sl -m 500 ${1+"$@"} \
 | sed -ne 's/[ 	][ 	]*/ /g
            s/^[^ ]*  *//;
            s=\([0-9]*\) \([^ ]*\) \(.*\)=\2 \3 \1=
            h
            s/ .*//

            G
            s/\(.*\)\(\n\).*/\2\1./
            :1
              s/\(.*\)\(\n.*[@.]\)\([^@.][^@.]*[@.]\)$/\1\3\2/
            t 1
            s/\n//
            s/\.$//

            G
            s/\n[^ ]*  */ /
            p
            ' \
 | sort -u +0 \
 | sed -ne 'h
            s/ .*//

            G
            s/\(.*\)\(\n\).*/\2\1./
            :1
              s/\(.*\)\(\n.*[@.]\)\([^@.][^@.]*[@.]\)$/\1\3\2/
            t 1
            s/\n//
            s/\.$//

            G
            s/\n[^ ]*  *//
            s=^=ftp://=
            p' \
 | awk '{ printf("%8s %s\n", $2, $1)}'

# marchie ends here
