#!/usr/bin/env bash

# Wrapper around `dd' to join args with `=' where required.
# This makes it easier to do filename completion on args without changing
# the syntax of `=' in emacs, since that is a valid file name character.

dd_op=( if ibs iflag    bs cbs conv
        of obs oflag    seek skip count status )

member()
{
    declare -n list=$2
    local arg
    for arg in "${list[@]}"; do
        case $arg in $1 ) return 0 ;; esac
    done
    return 1
}

main()
{
    declare -a ddarg=()
    while [ $# -gt 0 ]; do
        if member "$1" dd_op; then
            ddarg+=( "$1=$2" )
            shift
        else
            ddarg+=( "$1" )
        fi
        shift
    done

    exec ${DD-dd} "${ddarg[@]}"
}

main "$@"

# eof
