#!/usr/bin/env bash

base_fmt='%8i %7k  %M  %2n  %-7u  %-7g  %10s  %TY-%Tm-%Td %TH:%TM:%TS %Tz  %p'
sym_fmt="${base_fmt} -> %l\n"
std_fmt="${base_fmt}\n"

print=(
    '('
        '(' -type l -printf "$sym_fmt" ')'
      -o
        '('         -printf "$std_fmt" ')'
    ')'
)


find=$( type -p gfind || echo find  )
args=()

for arg in "$@"; do
    case $arg in
        -ls ) args+=( "${print[@]}" ) ;;
        *   ) args+=( "$arg" ) ;;
    esac
done

exec "$find" "${args[@]}"

# eof
