#!/bin/sh
# $Id: mkcd,v 1.2 2005/10/25 18:04:22 friedman Exp $

if ! [ -f .mkisofsrc ] && ! [ -f "$HOME/.mkisofsrc" ] ; then
  # If .mkisofsrc exists, don't override those settings on the command line.
  # On the other hand if the file doesn't exist, don't use any internal
  # defaults from mkisofs.
  set fnord         \
      -A         '' \
      -abstract  '' \
      -biblio    '' \
      -copyright '' \
      -p         '' \
      -publisher '' \
      -sysid     '' \
      -V         '' \
      -volset    '' \
      ${1+"$@"}
  shift
fi

exec mkisofs                         \
    -v -v                            \
    -r                               \
    -J                               \
    -T                               \
    -table-name TRANS.TBL            \
    -hide-joliet-trans-tbl           \
    -hide-rr-moved                   \
    -input-charset  iso8859-1        \
    -output-charset iso8859-1        \
    -pad                             \
    -no-bak                          \
    ${1+"$@"}

# mkcd ends here
