#!/usr/bin/env perl
# $Id$

$^W = 1; # enable warnings

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use lib "$ENV{HOME}/lib/perl";

use NF::FileUtil qw(:file);

$NF::FileUtil::verbose = 1;

sub main
{
  mklinktree ($_[0], $_[1]);
}

main (@ARGV);

1;
