#!/bin/sh
# monthconv -- convert month name to numeric equivalent or vice-versa
# Author: Noah Friedman <friedman@prep.ai.mit.edu>
# Created: 1994-03-09
# Public domain

sedstr='
  y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/
  s/^\(...\).*/\1/
  /^[0-9]*$/{
     /^1$/s/.*/Jan/
     /^2$/s/.*/Feb/
     /^3$/s/.*/Mar/
     /^4$/s/.*/Apr/
     /^5$/s/.*/May/
     /^6$/s/.*/Jun/
     /^7$/s/.*/Jul/
     /^8$/s/.*/Aug/
     /^9$/s/.*/Sep/
     /^10$/s/.*/Oct/
     /^11$/s/.*/Nov/
     /^12$/s/.*/Dec/
     p;q
  }
  /jan/s/.*/1/
  /feb/s/.*/2/
  /mar/s/.*/3/
  /apr/s/.*/4/
  /may/s/.*/5/
  /jun/s/.*/6/
  /jul/s/.*/7/
  /aug/s/.*/8/
  /sep/s/.*/9/
  /oct/s/.*/10/
  /nov/s/.*/11/
  /dec/s/.*/12/
  p;q
'

case $# in
  0 ) sed -ne "$sedstr" ;;
  * ) echo ${1+"$@"} | sed -ne "$sedstr" ;;
esac

# monthconv ends here
