#!/bin/sh
# osd-msg --- show text or percentage message onscreen
# Author: Noah Friedman <friedman@splode.com>
# Created: 2010-10-02
# Public domain

# $Id: osd-msg,v 1.2 2015/10/11 03:40:47 friedman Exp $

kill_prior()
{
    if [ -f $pidfile ]; then
        read pid < $pidfile
        if [ -d /proc/$$ ]; then
            # If we have /proc we can examine the process name and make
            # sure we don't accidentally kill something else just because
            # the pidfile is stale.
            if [ -d /proc/$pid ]; then
                read procname < /proc/$pid/comm
                case $procname in
                    $1 | */$1 ) kill $pid ;;
                esac
            fi
        else
            kill -0 $pid 2> /dev/null && kill $pid
        fi
    fi
}

find_display_font()
{
    # n.b. osd_cat isn't unicode-aware, so use 8bit charsets
    for attempt in \
        '-*-dejavu sans-medium-r-*-*-20-*-*-*-*-*-iso8859-1'           \
        '-*-dejavu sans condensed-medium-r-*-*-24-*-*-*-*-*-iso8859-1' \
        '-*-bitstream vera sans-medium-r-*-*-24-*-*-*-*-*-iso8859-1'   \
        '-xos4-terminus-bold-r-normal--20-200-72-72-c-100-iso8859-1'   \
        '-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1'
    do
        # Examine stderr from xlsfonts and if it's quiet, we have it.
        # A non-zero exit status from grep means there was error outout
        if ! xlsfonts -fn "$attempt" 2>&1 >/dev/null | grep . > /dev/null
        then
            font=$attempt
            return
        fi
    done
    echo "${0##*/}: Cannot find any font to use." 1>&2
    exit 1
}

_osd_cat()
{
    kill_prior osd_cat
    find_display_font
    osd_cat --color  green \
            --pos    bottom \
            --offset 100 \
            --indent  60 \
            --delay    3 \
            --shadow   2 \
            --lines    2 \
            --font   "$font" \
            ${1+"$@"} > /dev/null &

    echo $! > $pidfile
}

notify()
{
    echo "$*" > $txtfile
    _osd_cat $txtfile
}

pct()
{
    pct=$1
    shift
    _osd_cat --barmode percentage --percentage "$pct" --text "$*"
}

setup()
{
    umask 077

    uid=${UID:-`id -u`}
    if [ -d /run/user/$uid ]; then
        # linux systemd-logind 219 or later
        prefix=/run/user/$uid
    else
        prefix=${TMPDIR-/tmp}
    fi

    pidfile=$prefix/.osg-msg.$uid.pid
    txtfile=$prefix/.osg-msg.$uid.txt
}

main()
{
    setup
    case $1 in
        pct | notify )        ${1+"$@"} ;;
        *            ) notify ${1+"$@"} ;;
    esac
}

main ${1+"$@"}

# eof
