#!/usr/bin/env perl
# path --- split path into separate entries, one per line

# $Id$

# Author: Noah Friedman <friedman@splode.com>
# Created: 2008-08-05
# Public domain.

$^W = 1; # enable warnings

use strict;

sub main
{
  local $_ = @_ ? shift : "PATH" ;

  if    (m/:/)                {                  }
  elsif (defined $ENV{$_})    { $_ = $ENV{$_}    }
  elsif (defined $ENV{uc $_}) { $_ = $ENV{uc $_} }
  else                        { exit (1)         }

  s/:/\n/g;
  print $_, "\n";

}

main (@ARGV);

# path ends here
