#!/usr/bin/env perl
# $Id$

use strict;
use FindBin;

use lib "$FindBin::Bin/../../lib/perl";
use lib "$ENV{HOME}/lib/perl";

use NF::FileUtil qw(:search);

$^W = 1;  # enable warnings

sub main
{
  my @result = path_search ($_[0],
                            test => $_[1],
                            all  => $_[2]);

  map { print $_, "\n" } @result;
}

main (@ARGV);
