#!/usr/bin/env python
# $Id: pystrings,v 1.1 2018/10/06 00:17:20 friedman Exp $

from __future__ import print_function

import fileinput
import re
import sys

def openhook( name, mode ):
    try:
        return open( name, mode )
    except IOError as e:
        print( e.filename, e.strerror, sep=': ', file=sys.stderr )
        return open( '/dev/null', mode )

def main():
    pattern = re.compile( b'([\x20-\x7e\t ]{4,})' )
    for line in fileinput.input( mode='rb', openhook=openhook ):
        for match in pattern.findall( line ):
            print( match.decode() )

if __name__ == '__main__':
    try:
        main()
    except IOError as e:
        print( e, file=sys.stderr )
        sys.exit( 13 )  # sigpipe
    except KeyboardInterrupt:
        sys.exit( 130 ) # sigint

# eof
