#!/bin/sh
# rdp --- Remote Desktop Protocol client wrapper
# Author: Noah Friedman <friedman@splode.com>
# Created: 2005-08-10
# Public domain

# $Id: rdp,v 1.7 2011/05/19 01:25:08 friedman Exp $

# Commentary:

# When a client connects to a windows 2000/2003 terminal server and has no
# permanent client access license associated with it, the server will issue
# a temporary license.  This license will eventually expire and the client
# will no longer be able to connect.  This script adds a "generation
# number" to the client name (normally the host name) periodically to avoid
# using an expired temporary license.  The generation number is determined
# from the current date and time.

# The arg "-fs" will create a full-screen client.

# Code:

setup()
{
  hostname=${HOSTNAME-`uname -n`}
  host=`echo "$HOSTNAME" | sed -e 's/\..*//'`

  sec_per_day=86400
  days_per_license=60  # might be 90? play it safe
  epoch=1117584000     # 2005-06-01 00:00:00 UTC
  now=`date -u +%s`

  # expr is more likely to be installed than dc
  #gen=`echo "$now $epoch - $sec_per_day $days_per_license 1 - * / p" | dc`
  #gen=`expr \( $now - $epoch \) / \( $sec_per_day \* \( $days_per_license - 1 \) \)`
  gen=$(( (now - epoch) / (sec_per_day * (days_per_license - 1)) ))
  client=$host'$'$gen'$'

  xrdb=`xrdb -symbols -screen | sort`
  depth=`echo "$xrdb" | sed -n -e '/-DPLANES=/s///p'`
  case $depth in
    24 ) depth=32 ;;
  esac

  #geom=`xrdb-symbol-value WIDTH HEIGHT | sed -ne '1h;2H;$x;$s/\n/x/;$p'`
  geom=`echo "$xrdb" \
         | sed -e /-DHEIGHT=/h \
               -e /-DWIDTH=/H  \
               -e '$!d'        \
               -e x            \
               -e 's/^.*=\(.*\)\n.*=\(.*\)/\2x\1/'`
  display_geom=$geom

  case $1 in -fs ) return ;; esac
  case $geom in
    2560x1600 ) geom=1400x1050 ;;
    1920x1200 ) geom=1400x1050 ;;
    1600x1200 ) geom=1400x1050 ;;
    1680x1050 ) geom=1400x960  ;;
    1400x1050 ) geom=1280x960  ;; # use a 4:3 geometry
    1280x1024 ) geom=1152x864  ;; # note 1280x1024 is 5:4, not 4:3
    1152x864  ) geom=1024x768  ;;
    1024x600  ) geom=800x480   ;;
    1024x768  ) geom=800x600   ;;
     800x600  ) geom=640x480   ;;
  esac
}

run_rdesktop()
{
  case $1 in
    -fs ) shift
          set fnord -T notitle "$@"
          shift ;;
  esac

  ${RDP_PROG-rdesktop} \
      -n ${RDP_CLIENT-$client} \
      -g ${RDP_GEOM-$geom} \
      -u ${RDP_USER-${LOGNAME-$USER}} \
      -a ${RDP_DEPTH-$depth} \
      -K -P -z \
      ${1+"$@"} &
}

run_xfreerdp()
{
  case $1 in
    -fs ) shift
          set fnord -f "$@"
          shift ;;
  esac

  ${RDP_PROG-xfreerdp} \
      -n ${RDP_CLIENT-$client} \
      -g ${RDP_GEOM-$geom} \
      -u ${RDP_USER-${LOGNAME-$USER}} \
      -a ${RDP_DEPTH-$depth} \
      -z \
      --plugin cliprdr \
      --plugin rdpsnd \
      ${1+"$@"} &
}

main()
{
  setup "$@"
  case ${RDP_PROG-rdesktop} in
    *rdesktop* ) run_rdesktop "$@" ;;
    *freerdp*  ) run_xfreerdp "$@" ;;
  esac
}

main "$@"

# eof
