#! /bin/sh
# rotate-log --- rotate accounting logs, optionally compressing old logs
# Author: Noah Friedman <friedman@prep.ai.mit.edu>
# Created: 1992-02-10
# Public domain

# $Id: rotate-log,v 1.6 1995/04/30 20:01:43 friedman Exp friedman $

# Commentary:
# Code:

# Name by which this script was invoked.
progname=`echo "$0" | sed -e 's/[^\/]*\///g'`

# To prevent hairy quoting and escaping later.
bq='`'
eq="'"

usage="Usage: $progname {options} [logfile-name ...]

Options are:
-c, --compress                Compress old logs while rotating.
-C, --compress-active         Compress the active log (which will be
                              rotated to log.0).  Normally this isn't done
                              because it may cause a race condition if the
                              file is still open, e.g. for process
                              accounting, syslogs, etc.  Exercise caution
                              using this option.
                              This option implies --compress.
-D, --debug                   Turn on shell debugging ($bq${bq}set -x$eq$eq).
-d, --default-directory  DIR  Default directory for log files listed without
                              pathname (i.e. no "/" chars in name)
-g, --group, --chgrp   GROUP  Change group ownership to GROUP on rotated logs.
-h, --help                    You're looking at it.
-M, --compress-method METHOD  Method to use for compressing; one of
                              ${bq}compact$eq, ${bq}compress$eq, ${bq}gzip$eq.
                              Default is ${bq}compress$eq.
-m, --mode, --chmod     MODE  Change permissions to MODE on rotated logs.
-n, --number-of-logs       N  Keep up to N versions of log total (default 7).
                              Rotated logs are numbered zero-origin.
-o, --owner, --chown   OWNER  Change owner of logs to OWNER (you should use
                              OWNER.GROUP and avoid using --group if the
                              ${bq}chown${eq} command supports this syntax).
-v, --verbose                 Chatter away while working.
"

# Usage: eval "$getopt"; value=$optarg
# or     optarg_optional=t; eval "$getopt"; value=$optarg
#
# This function automatically shifts the positional args as appropriate.
# The argument to an option is optional if the variable `optarg_optional'
# is non-empty.  Otherwise, the argument is required and getopt will cause
# the program to exit on an error.  optarg_optional is reset to be empty
# after every call to getopt.  The argument (if any) is stored in the
# variable `optarg'.
#
# Long option syntax is `--foo=bar' or `--foo bar'.  2nd argument
# won't get used if first long option syntax was used.
#
# Note: because of broken bourne shells, using --foo=bar syntax can
# actually screw the quoting of args that end with trailing newlines.
# Specifically, most shells strip trailing newlines from substituted
# output, regardless of quoting.
getopt='
  {
    optarg=
    case "$1" in
      --*=* )
        optarg=`echo "$1" | sed -e "1s/^[^=]*=//"`
        shift
       ;;
      * )
        case ${2+set} in
          set )
            optarg="$2"
            shift
            shift
           ;;
          * )
            case "$optarg_optional" in
              "" )
                case "$1" in
                  --*=* ) option=`echo "$1" | sed -e "1s/=.*//;q"` ;;
                  * ) option="$1" ;;
                esac
                exec 1>&2
                echo "$progname: option $bq$option$eq requires argument."
                echo "$progname: use $bq--help$eq to list option syntax."
                exit 1
               ;;
           esac
         ;;
        esac
     ;;
    esac
    optarg_optional=
  }'

# Initialize variables.
# Don't use `unset' since old bourne shells don't have this command.
# Instead, assign them an empty value.
chgrp=:
chmod=:
chown=:
compressp=
compress_activep=
compress_method=compress
debug=
default_directory=.
number_of_logs=7
verbose=

# Parse command line arguments.
# Make sure that all wildcarded options are long enough to be unambiguous.
# It's a good idea to document the full long option name in each case.
# Long options which take arguments will need a `*' appended to the
# canonical name to match the value appended after the `=' character.
while : ; do
  case $# in 0) break ;; esac
  case "$1" in
    -C | --compress-active | --compress-a* )
      compressp=t
      compress_activep=t
      shift
     ;;
    -c | --compress )
      compressp=t
      shift
     ;;
    -D | --debug | --deb* )
      debug=t
      shift
     ;;
    -d | --default-directory* | --def* )
      eval "$getopt"
      default_directory="$optarg"
     ;;
    -g | --group | --g* | --chgrp* | --chg* )
      eval "$getopt"
      chgrp="${CHGRP-chgrp} $optarg"
     ;;
    -M | --compress-method* | --compress-m* )
      eval "$getopt"
      compress_method="$optarg"
     ;;
    -m | --mode | --m* | --chmod* | --chm* )
      eval "$getopt"
      chmod="${CHMOD-chmod} $optarg"
     ;;
    -n | --number-of-logs* | --n* )
      eval "$getopt"
      number_of_logs="$optarg"
     ;;
    -o | --owner | --o* | --chown* | --cho* )
      eval "$getopt"
      chown="${CHOWN-chown} $optarg"
     ;;
    -v | --verbose | --v* )
      verbose=t
      shift
     ;;
    -h | --help | --h )
      echo "$usage" 1>&2
      exit 1
     ;;
    -- )     # Stop option processing
      shift
      break
     ;;
    -? | --* )
      case "$1" in
        --*=* ) arg=`echo "$1" | sed -e 's/=.*//'` ;;
        * )     arg="$1" ;;
      esac
      exec 1>&2
      echo "$progname: unknown or ambiguous option $bq$arg$eq"
      echo "$progname: Use $bq--help$eq for a list of options."
      exit 1
     ;;
    -??* )
      # Split grouped single options into separate args and try again
      optarg="$1"
      shift
      set fnord `echo "x$optarg" | sed -e 's/^x-//;s/\(.\)/-\1 /g'` ${1+"$@"}
      shift
     ;;
    * )
      break
     ;;
  esac
done

case "$debug" in t ) set -x ;; esac

case $# in
  0 )
    echo "$progname: at least one log name is required as an argument." 1>&2
    echo "$usage" 1>&2
   ;;
esac

case "$compress_method" in
  compact )  compress_cmd='compact -f';  suffix='.C'  ;;
  compress ) compress_cmd='compress -f'; suffix='.Z'  ;;
  gzip )     compress_cmd='gzip';        suffix='.gz' ;;
  * )
    echo "$progname: unknown compress-method $bq$compress_method$eq" 1>&2
    exit 1
   ;;
esac

orig_cwd=${PWD-`pwd`}
max_log_number=`expr $number_of_logs - 1`  # make it zero-origin

for log in ${1+"$@"} ; do
  cd "$orig_cwd"

  dirname=`echo "$log" \
           | sed -e 's/\/*$//
                     s/\/[^\/]*$//'`
  basename=`echo "$log" \
            | sed -e 's/\/*$//
                      s/.*\///'`
  case "$dirname" in "$basename" )
    dirname=$default_directory ;;
  esac

  if cd "$dirname" ; then
    :
  else
    echo "$progname: skipping $bq$log$eq logs." 1>&2
    continue
  fi

  if test ".$compressp" = '.t' ; then
    num=$max_log_number
    while : ; do
      case $num in -1 ) break ;; esac
      file="$basename.$num"

      test -f "$file" \
       && $compress_cmd "$file" \
       && test ".$verbose" = '.t' \
       && echo "$file -> $file$suffix"

      num=`expr $num - 1`
    done
  else
    suffix=
  fi

  num=$max_log_number
  nextnum=$number_of_logs
  while : ; do
    case $num in
      -2 ) break ;;
      -1 )
        oldfile="$basename"
        newfile="$basename.0"
       ;;
      * )
        oldfile="$basename.$num$suffix"
        newfile="$basename.$nextnum$suffix"
       ;;
    esac

    test -f "$oldfile" \
     && test $nextnum -lt $max_log_number \
     && mv "$oldfile" "$newfile" \
     && {
          case "$verbose" in t )
            echo "$oldfile -> $newfile" ;;
          esac

          $chmod "$newfile"
          $chgrp "$newfile"
          $chown "$newfile"
        }

    nextnum=$num
    num=`expr $num - 1`
  done

  # Create new logfile (or rather, append to it just in case some other
  # random process has already created it and started writing into it)
  >> "$basename"
  $chmod "$basename"
  $chgrp "$basename"
  $chown "$basename"

  case "$compress_activep" in t)
    $compress_cmd "$basename.0" \
     && test ".$verbose" = '.t' \
     && echo "$basename.0 -> $basename.0$suffix"
  esac

  case "$verbose" in t )
    echo "Created $basename" ;;
  esac
done

# rotate-log ends here
