#!/bin/sh
# $Id: rpm-pkg-list,v 1.1 2004/11/29 02:18:16 friedman Exp $

case $1 in
  -size    | size    ) k='-k1,1n -k2,2'  ; shift ;;
  -version | version ) k='-k3,3n -k2,2'  ; shift ;;
  -name    | name    ) k='-k2,2  -k1,1n' ; shift ;;
  * )                  k='-k2,2  -k1,1n'         ;;
esac

case $# in 0 ) set '*' ;; esac

a=
case $* in *[*?]* ) a=-a ;; esac # faster if no globbing

fmt='%{SIZE} %{NAME} %{VERSION}-%{RELEASE} %{ARCH}\n'

rpm --qf "$fmt" -q $a ${1+"$@"} \
 | sort -f $k \
 | fmtcols -Nw

# eof
