#!/bin/sh
# rpm-gpg-fingerprints -- display fingerprint and key descriptions
# Author: Noah Friedman <friedman@splode.com>
# Created: 2014-01-25
# Public domain

rpm --nodigest \
    --nosignature \
    --qf '%{version}\t%{summary}\n' \
    -q gpg-pubkey \
    "$@" \
| sed -e 's/gpg(//;s/)$//' \
| sort -k2V

# eof
