#!/bin/sh

: ${RSYNC:=rsync}
: ${RSYNC_RSH:=ssh}
export RSYNC_RSH

case $* in
    *-quiet*   ) : ;;
    *          ) set : --verbose "$@" ; shift ;;
esac

case $* in
    *-inplace* ) : ;;
    *          ) set : --sparse  "$@" ; shift ;;
esac

case ${RS_UID-${UID-`id -u`}} in
    0          ) set : --devices "$@"
                 shift
                 case ${U_SYSTEM-`uname -s`} in
                     Linux ) set : \
                                 --acls \
                                 --xattrs \
                                 --filter='-x security.selinux' \
                                 "$@"
                             shift ;;
                 esac ;;
esac

set : \
    --owner		\
    --group		\
    --perms		\
    --times		\
			\
    --hard-links	\
    --links		\
			\
    --delete		\
    --force		\
			\
    --recursive		\
    "$@"
shift

if [ -t 0 ]; then
    $RSYNC -n "$@" | sed -e 's/^/[PROPOSED] /'
    echo
    echo -n "Is this what you want (y/N)? "
    read resp
    case $resp in
        [Yy]* ) : ;;
        * ) exit 1 ;;
    esac
fi

echo + $RSYNC "$@" 1>&2
exec $RSYNC "$@"

# eof
