#!/bin/sh

RSYNC_RSH=${RSYNC_RSH-ssh}
export RSYNC_RSH

case $* in
  *-quiet* ) : ;;
  *          ) set : --verbose "$@" ; shift ;;
esac

case $* in
  *-inplace* ) : ;;
  *          ) set : --sparse  "$@" ; shift ;;
esac

case ${RS_UID-${UID-`id -u`}} in
  0          ) set : --devices "$@" ; shift ;;
esac

set : \
    --owner		\
    --group		\
    --perms		\
    --times		\
			\
    --hard-links	\
    --links		\
			\
    --delete		\
    --force		\
			\
    --recursive		\
    "$@"
shift

if [ -t 0 ]; then
    ${RSYNC-rsync} -n "$@" | sed -e 's/^/[PROPOSED] /'
    echo
    echo -n "Is this what you want (y/N)? "
    read resp
    case $resp in
        [Yy]* ) : ;;
        * ) exit 1 ;;
    esac
fi

exec ${RSYNC-rsync} "$@"

# eof
