#!/bin/sh
# sizeof -- print size of standard C types
# Author: Noah Friedman <friedman@splode.com>
# Created: 2007-03-23
# Public domain.

# $Id: sizeof,v 1.2 2017/08/18 00:28:45 friedman Exp $

# Commentary:
# Code:

cd ${TMPDIR-/tmp} || exit 1

file="sizeof$$"
trap 'rm -f $file $file.[co]' 0 1 2 3 15

type=$1
shift

cat > $file.c <<- __EOF__
	#include <stdio.h>
	#include <sys/types.h>
`for h in "$@"; do echo "	#include <$h>"; done`
	int main ()
	{
	    printf ("%ld\n", sizeof ($type));
	    return 0;
	}
__EOF__

${CC-cc} $CFLAGS $file.c -o $file && ./$file

# eof
