#!/usr/bin/env python3
# slowcat --- write output slowly, emulating dialup terminal
# Author: Noah Friedman <friedman@splode.com>
# Created: 2003-01-01
# Public domain


import argparse
import os
import sys
from   time import sleep


def get_args():
    p = argparse.ArgumentParser()
    p.add_argument( '-b', '--bps', type=int, default=9600 )
    p.add_argument( 'files', nargs='*' )
    return p.parse_args()


def slowcat( ifh, bps ):
    ofd = sys.stdout.fileno()
    interval = 8 / bps
    while c := ifh.read( 1 ):
        os.write( ofd, c )
        sleep( interval )


def main():
    args = get_args()
    if not args.files:
        slowcat( sys.stdin.buffer, args.bps )
    else:
        err = 0
        for file in args.files:
            try:
                slowcat( open( file, 'rb' ), args.bps )
            except OSError as diag:
                print( diag, file=sys.stderr )
                err = min( 127, err + 1 )
        return err


if __name__ == '__main__':
    try:
        sys.exit( main() )
    except KeyboardInterrupt:
        sys.exit( (1<<7) | 2 )


# eof
