#!/bin/sh
# smtp --- kludgy hack to connect to smtp servers by abbreviated hostname
# Author: Noah Friedman <friedman@prep.ai.mit.edu>
# Created: 1995-04-15
# Public domain

# $Id: smtp,v 1.4 1996/04/03 15:13:19 friedman Exp $

case "$1" in
  aeneas )             h=aeneas.mit.edu            ;;
  athena )             h=athena.mit.edu            ;;
  ccwf )               h=ccwf.cc.utexas.edu        ;;
  cli )                h=cli.com                   ;;
  cyclic | totoro )    h=cyclic.com                ;;
  es | rc )            h=hawkwind.utcs.toronto.edu ;;
  floss )              h=floss.cyclic.com          ;;
  frob | baal )        h=frob.com                  ;;
  gnu | albert)        h=albert.gnu.ai.mit.edu     ;;
  lcs | mintaka )      h=mintaka.lcs.mit.edu       ;;
  mc )                 h=mc.lcs.mit.edu            ;;
  media )              h=media.mit.edu             ;;
  prep | ai | life )   h=life.ai.mit.edu           ;;
  osu | cis )          h=cis.ohio-state.edu        ;;
  piglet )             h=piglet.splode.com         ;;
  splode )             h=splode.mame.mu.oz.au      ;;
  * )                  h="$1"                      ;;
esac

exec tcpconnect -v $h smtp

# smtp ends here
