#! /bin/sh
# $Id$

# multiline is a dig 9.x option; ignore error in older versions because
# they print soa entries in multiline format already anyway.
dig "$1" soa +multiline 2> /dev/null \
 | sed -ne "/^$dom.*SOA/{
              :l
              /;.*serial/!{
                n
                b l
              }
              s/^[^0-9]*\([0-9][0-9]*\)[^0-9]*/\1/p
              q
            }"
