#! /bin/sh

dom="$1"

dig "$dom" soa \
 | sed -ne "/^$dom.*SOA/{
              :l
              /;.*serial/!{
                n
                b l
              }
              s/^[^0-9]*\([0-9][0-9]*\)[^0-9]*/\1/p
              q
            }"
