#!/bin/sh
# $Id: ssh-add-all,v 1.4 2004/02/17 08:49:27 friedman Exp $

foundp=f
for dir in $HOME/etc/certs/ssh $HOME/.ssh/certs ; do
  if [ -d "$dir" ]; then
    cd "$dir" || continue
    foundp=t
    break
  fi
done
test $foundp != t && exit 0

if [ -f .load-certs ]; then
  ids=`cat .load-certs`
else
  ids=`echo *`
fi

for id in $ids; do
  for key in id_rsa id_dsa identity ; do
    if [ -f $id/$key ]; then
      ssh-add $id/$key
    fi
  done
done

# eof
