#!/bin/sh
# $Id: ssh-rexec,v 1.2 2004/02/25 10:41:34 friedman Exp $

params='
  FallBackToRsh=no
  EscapeChar=none
  ForwardAgent=no
  ForwardX11=no
  Compression=no
  BatchMode=yes
  Protocol
  Port
  User
'

for param in $params ; do
  param=`echo $param \
          | sed -e '/=/!{s/^/default= option=/;q;}' \
                -e 's/^\([^=]*\)=\(.*\)/option=\1 default=\2/'`
  eval $param

  var=SSH_REXEC_`echo $option | tr '[a-z]' '[A-Z]'`
  eval val=\${$var-$default}
  case $val in
    '' ) : ;;
    * )
      set fnord -o "$option $val" ${1+"$@"}
      shift
     ;;
  esac
done

for ident in $SSH_REXEC_IDENTITIES ; do
  set fnord -i $ident ${1+"$@"}
  shift
done

case ${SSH_REXEC_CONFIG+set} in
  set )
    set fnord -F "$SSH_REXEC_CONFIG" ${1+"$@"}
    shift
   ;;
esac

exec ${SSH_REXEC-ssh} ${1+"$@"}

# eof
