#!/bin/sh
# $Id: stty-canon,v 1.3 2012/08/28 23:15:53 friedman Exp $
# Public domain.

#stty_canon()
{
    # These are issued as a series of separate commands in case some of
    # them aren't recognized; stty might not evaluate the rest of the
    # arguments.

    stty icanon tabs
    stty intr '^C' kill '^U' quit '^\\' eof '^D'
    stty susp '^Z'
    stty -ixon -ixoff -ixany
    stty onlcr -ocrnl -onlret

    case $1 in
        -safe ) shift ;;
        # these settings can make some terminals unusable.
        *     ) stty cs8 -istrip -iexten -parenb ;;
    esac

    case ${INSIDE_EMACS-$EMACS}:$TERM in
        *:xterm* )
            stty erase '^?'
            stty opost 2> /dev/null ;;

         :* ) : ;;
        *:* ) stty -icrnl -inlcr -onlcr -echo ;;
    esac

    case $# in
        0 ) : ;;
        * ) stty ${1+"$@"} ;;
    esac
}

#stty_canon ${1+"$@"}

# eof
