#! /bin/sh
# tex2text --- convert TeX to ascii
# Author: Noah Friedman <friedman@prep.ai.mit.edu>
# Created: 1996-01-11
# Public domain

# $Id: tex2text,v 1.1 1996/01/12 01:20:52 friedman Exp $

for texfile in ${1+"$@"}; do
  case "$texfile" in
    *.tex )
      base=`basename $texfile .tex`
      tex $texfile
     ;;
    *.dvi )
      base=`basename $texfile .dvi`
     ;;
    * )
      base=$texfile
      if test -f $texfile.dvi ; then
        :
      elif test -f $texfile.tex ; then
        tex $texfile.tex
      fi
     ;;
  esac

  dvi2tty $base.dvi \
   | sed -ne '/\*$/!{p;d;}
              h
              n
              H
              x
              s/\*\n \*//
              p
             ' > $base.txt
done

# tex2text ends here
