#!/usr/bin/env perl
# $Id: tinyurl,v 1.1 2009/08/27 20:07:19 friedman Exp $

$^W = 1; # enable warnings

use LWP;
use URI;
use strict;

sub http_get
{
  my ($url) = @_;

  my $request = HTTP::Request->new ('GET');
  my $ua      = LWP::UserAgent->new;
  my $uri     = URI->new ($url);
  $request->url ($uri);
  $ua->env_proxy;
  my $response = $ua->request ($request);
  return $response->content;
}

sub main
{
  my $u = "http://tinyurl.com/api-create.php?url=";
  map { print http_get ($u . $_), "\n" } @_;
}

main (@ARGV);

# eof
