#!/bin/sh
# $Id$

if test $# -eq 0 ; then
  sed -e '1,/^[:#]/d' | sh
else
  for f in ${1+"$@"} ; do
    case "$f" in
      *.gz | *.z | *.Z )
        gzip -d < "$f" | sed -e '1,/^[:#]/d' | sh
       ;;
      * )
       sed -e '1,/^[:#]/d' "$f" | sh
      ;;
    esac
  done
fi
