#! /bin/sh
# $Id: untar,v 1.14 2008/02/07 01:02:21 friedman Exp $

for f in ${1+"$@"}; do
  case "$f" in
    *.t[ag]z | *.tar.gz | *.tar.[Zz] | *.xtar.gz | *.xtar.[Zz] | *.nif )
      ${GZIP-gzip} -dc "$f" | ${TAR-tar} -xpvf -
     ;;

    *.tbz | *.tbz2 | *.tar.bz2 | *.xtar.bz2 | *.tar.bz | *.cbt )
      ${BZIP2-bzip2} -dc "$f" | ${TAR-tar} -xpvf -
     ;;

    *.tar.lzma )
      ${LZMA-lzma} -dc "$f" | ${TAR-tar} -xpvf -
     ;;

    *.tar | *.xtar )
      ${TAR-tar} -xpvf "$f"
     ;;

    *.zip | *.jar | *.cbz | *.fbu )
      ${UNZIP-unzip} -o "$f"
     ;;

    *.rpm )
      ${RPM2CPIO-rpm2cpio} "$f" | ${CPIO-cpio} -dimv --no-absolute-filenames
     ;;

    *.lzh )
      ${LHA-lha} x "$f"
     ;;

    *.rar | *.cbr )
      ${UNRAR-unrar} x "$f"
     ;;

    *.a | *.lib )
      libdir=`echo "$f" | sed -e 's/\.[^.]*$//'`
      case "$f" in
        /* ) : ;;
        *  ) f=../$f ;;
      esac
      mkdir -p $libdir
      (cd $libdir && ${AR-ar} xv "$f")
     ;;
  esac
done

# eof
