#!/bin/sh

# $Id: wget,v 1.5 2006/11/21 20:36:56 friedman Exp $

wget=`run-next -p "$0" || echo :`

# Many websites block wget based on user agent.  So fabricate a different one.
#user_agent='Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US; rv:1.8.1) Gecko/20061010 Firefox/2.0'
user_agent='Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1) Gecko/20061010 Firefox/2.0'

cookies=$HOME/etc/misc/.wget/cookies.txt

# Get major and minor version numbers for wget
eval `$wget --version \
        | sed -ne '1s/^.*get \([0-9]*\)\.\([0-9]*\).*/vmajor=\1 vminor=\2/p'`

case $vmajor:$vminor in
  : | *: | :* ) exit 1 ;;
esac

atleast() { [ $vmajor -eq $1 ] && [ $vminor -ge $2 ] || [ $vmajor -gt $1 ]; }

opts="--verbose
      --server-response
      --timestamping
      --wait=0
      --tries=0
      --cache=off
      --passive-ftp
     "
#     --follow-ftp

if atleast 1 6; then
  opts="$opts \
        --html-extension
        --waitretry=60
       "
fi

if atleast 1 7 && [ -f "$cookies" ]; then
  opts="$opts
        --cookies=on
        --load-cookies=$cookies
       "
  if [ -w "$cookies" ] && [ ! -h "$cookies" ]; then
    opts="$opts --save-cookies=$cookies"
  fi
fi

if atleast 1 8 && [ -t 1 ]; then
  # Use in-place progress bar if stdout is a tty
  opts="$opts --progress=bar:force"
fi

# Add timeout and retry options to wget 1.9 and later
if atleast 1 9; then
  opts="$opts
        --dns-timeout=30
        --connect-timeout=30
        --read-timeout=300

        --retry-connrefused
       "
       #--dns-cache=off
fi

exec $wget \
  --user-agent="$user_agent" \
  --execute 'robots = off' \
  $opts ${1+"$@"}

# wget ends here
