#!/bin/sh
# $INITBIN/where, 17-Jul-91 Noah Friedman <friedman@prep.ai.mit.edu>
#
# Find all instances of a file name in the path.  Note: If you are using
# bash, it is strongly recommended that you use a function taking advantage
# of builtin features instead, as they are noticeably faster.  See
# $INIT/functions.
#
# Public domain.
#

if [ ! "$1" ]; then
    echo "Usage: which {commandname}"
    exit 1
fi

path=`echo ${PATH} | sed -e 's=^:=.:=;s=::=:.:=g;s=:$=:.=;s=:= =g'`

found=0
for p in ${path} ; do
   if [ -f ${p}/$1 ]; then
      echo ${p}/$1
      found=1
   fi
done

if [ ${found} -eq 0 ]; then 
   exit 2
fi

#
# eof
#
