#!/bin/sh
#
# $INITBIN/which, 17-Jul-91 Noah Friedman <friedman@prep.ai.mit.edu>
#
# Determine determine first directory in the path where a file name is
# located.  Note: If you are using bash, it is strongly recommended that
# you use a function taking advantage of builtin features instead, as they
# are noticeably faster.  See $INIT/functions.
#
# Public domain.
#

if [ ! "$1" ]; then
    echo "Usage: where {commandname}"
    exit 1
fi

path=`echo ${PATH} | sed -e 's=^:=.:=' -e 's=::=:.:=g' -e 's=:$=:.=' -e 's=:= =g'`

for p in ${path} ; do
   if [ -f "${p}/$1" ]; then
      echo "${p}/$1"
      exit
   fi
done

exit 2

#
# eof
#
