#! /bin/sh

# $Id: wsnarf,v 1.5 2004/11/24 00:19:18 friedman Exp $

exec wget           \
  --convert-links   \
  --force-html      \
  --no-parent       \
  --recursive       \
  --level=0         \
  "$@"

# wsnarf ends here
