#!/bin/sh
# $Id: xbiffpop,v 1.1 1996/10/18 16:07:49 friedman Exp $

# Name by which this script was invoked.
progname=`echo "$0" | sed -e 's/[^\/]*\///g'`

umask 077

prog=/tmp/$progname$$
stateinfo=${prog}.data

echo 0 > $stateinfo

cat > $prog <<__EOF__
#!/bin/sh

oldsize=\`cat $stateinfo\`
newsize=\`${FROM-from} -C\`

echo \$newsize > $stateinfo

# exit status:
#   0 = there is new mail
#   1 = no change in size
#   2 = mail has been cleared
case \$newsize in
  '' )        exit 1 ;;
  0  )        exit 2 ;;
  \$oldsize ) exit 1 ;;
  *  )        exit 0 ;;
esac
__EOF__

chmod +x $prog
exec xbiff -xrm "xbiff*checkCommand: $prog" ${1+"$@"}

# eof
