#!/bin/bash
# $Id: zfs-backup,v 1.1 2015/07/24 09:35:38 friedman Exp $

# To initialize iscsi target:
#	iscsictl -A -d wdmc-1.prv.splode.com
#	iscsictl -A -d obey-chomsky.prv.splode.com
#
# To bring iscsi backup pool online:
# 	zpool import [poolname]
#
# To take offline:
# 	zpool export [poolname]

lastsnap()
{
  zfs list -t snapshot -H -d 1 -o name -S name $1 \
   | sed -e '/@backup\./!d' \
         -e 's/.*@//' \
         -e q
}

mksnap()
{
  name=backup.`date +"%Y-%m-%d.%H:%M:%S"`
  zfs snapshot -r $1@$name
  echo $name
}

fslist()
{
  zfs list -H -r -o name "$@"
}

backup()
{
  srcpool=$1
  dstpool=$2

  oldsnap=`lastsnap $srcpool`
  newsnap=`mksnap $srcpool`

  for fs in `fslist $srcpool`; do
    date +"[%Y-%m-%d %H:%M:%S%z] Backing up $fs"
    time { zfs send ${oldsnap:+-I $oldsnap} $fs@$newsnap | zfs recv -F -v -d $dstpool; }
  done
  date +"[%Y-%m-%d %H:%M:%S%z] Done."
}

mirror()
{
  srcpool=$1
  dstpool=$2

  newsnap=`mksnap $srcpool`

  date +"[%Y-%m-%d %H:%M:%S%z] Mirroring $srcpool to $dstpool"
  zfs send -R $srcpool@$newsnap | zfs recv -F -v -d $dstpool
  date +"[%Y-%m-%d %H:%M:%S%z] Done."
}

main()
{
    PATH=/sbin:$PATH

    case $#:$3 in
        2:      ) backup "$@" ;;
        3:-full ) mirror "$@" ;;
        *       ) echo "Usage: ${0##*/} [srcpool] [dstpool]" 1>&2
                  exit 1 ;;
    esac
}

main "$@"

# eof
